---
- name: Deploy Flask Portfolio App
  hosts: webservers
  become: yes
  tasks:
    - name: Update apt cache and install python3-pip
      apt:
        update_cache: yes
        name: 
          - python3-pip
          - python3-venv
        state: present

    - name: Ensure app directory exists
      file:
        path: /opt/portfolio
        state: directory
        owner: "{{ ansible_user }}"

    - name: Copy app files to server
      copy:
        src: ../src/
        dest: /opt/portfolio/
        owner: "{{ ansible_user }}"

    - name: Install requirements
      pip:
        requirements: /opt/portfolio/requirements.txt
        executable: pip3

    - name: Create systemd service for Flask
      copy:
        dest: /etc/systemd/system/portfolio.service
        content: |
          [Unit]
          Description=Giga Tanio Portfolio Flask App
          After=network.target

          [Service]
          User={{ ansible_user }}
          WorkingDirectory=/opt/portfolio
          ExecStart=/usr/bin/python3 app.py
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Restart portfolio service
      systemd:
        name: portfolio
        state: restarted
        enabled: yes
        daemon_reload: yes